ALTER TABLE incident
  ADD COLUMN IF NOT EXISTS lat DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS lon DOUBLE PRECISION,
  ADD COLUMN seen boolean DEFAULT false;

ALTER TABLE user
  ADD COLUMN IF NOT EXISTS city TEXT NOT NULL,
  ADD COLUMN IF NOT EXISTS areas TEXT,
  ADD COLUMN IF NOT EXISTS  addressOfUser TEXT[];
    
    
   